/* SPDX-License-Identifer: GPL-2.0-only */
/* Copyright 2023 Michael Shaw */

/* 6502 Opcodes */

namespace cpu_6502;

public partial class cpu
{
	struct opcode {
		public instruction ins;
		public addrmode adm;
	};

	opcode[] opcodes = new opcode[256];

	void opcodes_populate()
	{
		opcodes[0] = new opcode { ins = new instruction(brk), adm = new addrmode(imp) };
		opcodes[1] = new opcode { ins = new instruction(ora), adm = new addrmode(inx) };
		opcodes[5] = new opcode { ins = new instruction(ora), adm = new addrmode(zpg) };
		opcodes[6] = new opcode { ins = new instruction(asl), adm = new addrmode(zpg) };
		opcodes[8] = new opcode { ins = new instruction(php), adm = new addrmode(imp) };
		opcodes[9] = new opcode { ins = new instruction(ora), adm = new addrmode(imm) };
		opcodes[10] = new opcode { ins = new instruction(asl_a), adm = new addrmode(a) };
		opcodes[13] = new opcode { ins = new instruction(ora), adm = new addrmode(abs) };
		opcodes[14] = new opcode { ins = new instruction(asl), adm = new addrmode(abs) };
		opcodes[16] = new opcode { ins = new instruction(bpl), adm = new addrmode(rel) };
		opcodes[17] = new opcode { ins = new instruction(ora), adm = new addrmode(iny) };
		opcodes[21] = new opcode { ins = new instruction(ora), adm = new addrmode(zpx) };
		opcodes[22] = new opcode { ins = new instruction(asl), adm = new addrmode(zpx) };
		opcodes[24] = new opcode { ins = new instruction(clc), adm = new addrmode(imp) };
		opcodes[25] = new opcode { ins = new instruction(ora), adm = new addrmode(aby) };
		opcodes[29] = new opcode { ins = new instruction(ora), adm = new addrmode(abx) };
		opcodes[30] = new opcode { ins = new instruction(asl), adm = new addrmode(abx) };
		opcodes[32] = new opcode { ins = new instruction(jsr), adm = new addrmode(abs) };
		opcodes[33] = new opcode { ins = new instruction(and), adm = new addrmode(inx) };
		opcodes[36] = new opcode { ins = new instruction(bit), adm = new addrmode(zpg) };
		opcodes[37] = new opcode { ins = new instruction(and), adm = new addrmode(zpg) };
		opcodes[38] = new opcode { ins = new instruction(rol), adm = new addrmode(zpg) };
		opcodes[40] = new opcode { ins = new instruction(plp), adm = new addrmode(imp) };
		opcodes[41] = new opcode { ins = new instruction(and), adm = new addrmode(imm) };
		opcodes[42] = new opcode { ins = new instruction(rol_a), adm = new addrmode(a) };
		opcodes[44] = new opcode { ins = new instruction(bit), adm = new addrmode(abs) };
		opcodes[45] = new opcode { ins = new instruction(and), adm = new addrmode(abs) };
		opcodes[46] = new opcode { ins = new instruction(rol), adm = new addrmode(abs) };
		opcodes[48] = new opcode { ins = new instruction(bmi), adm = new addrmode(rel) };
		opcodes[49] = new opcode { ins = new instruction(and), adm = new addrmode(iny) };
		opcodes[53] = new opcode { ins = new instruction(and), adm = new addrmode(zpx) };
		opcodes[54] = new opcode { ins = new instruction(rol), adm = new addrmode(zpx) };
		opcodes[56] = new opcode { ins = new instruction(sec), adm = new addrmode(imp) };
		opcodes[57] = new opcode { ins = new instruction(and), adm = new addrmode(aby) };
		opcodes[61] = new opcode { ins = new instruction(and), adm = new addrmode(abx) };
		opcodes[62] = new opcode { ins = new instruction(rol), adm = new addrmode(abx) };
		opcodes[64] = new opcode { ins = new instruction(rti), adm = new addrmode(imp) };
		opcodes[65] = new opcode { ins = new instruction(eor), adm = new addrmode(inx) };
		opcodes[69] = new opcode { ins = new instruction(eor), adm = new addrmode(zpg) };
		opcodes[70] = new opcode { ins = new instruction(lsr), adm = new addrmode(zpg) };
		opcodes[72] = new opcode { ins = new instruction(pha), adm = new addrmode(imp) };
		opcodes[73] = new opcode { ins = new instruction(eor), adm = new addrmode(imm) };
		opcodes[74] = new opcode { ins = new instruction(lsr_a), adm = new addrmode(a) };
		opcodes[76] = new opcode { ins = new instruction(jmp), adm = new addrmode(abs) };
		opcodes[77] = new opcode { ins = new instruction(eor), adm = new addrmode(abs) };
		opcodes[78] = new opcode { ins = new instruction(lsr), adm = new addrmode(abs) };
		opcodes[80] = new opcode { ins = new instruction(bvc), adm = new addrmode(rel) };
		opcodes[81] = new opcode { ins = new instruction(eor), adm = new addrmode(iny) };
		opcodes[85] = new opcode { ins = new instruction(eor), adm = new addrmode(zpx) };
		opcodes[86] = new opcode { ins = new instruction(lsr), adm = new addrmode(zpx) };
		opcodes[88] = new opcode { ins = new instruction(cli), adm = new addrmode(imp) };
		opcodes[89] = new opcode { ins = new instruction(eor), adm = new addrmode(aby) };
		opcodes[93] = new opcode { ins = new instruction(eor), adm = new addrmode(abx) };
		opcodes[94] = new opcode { ins = new instruction(lsr), adm = new addrmode(abx) };
		opcodes[96] = new opcode { ins = new instruction(rts), adm = new addrmode(imp) };
		opcodes[97] = new opcode { ins = new instruction(adc), adm = new addrmode(inx) };
		opcodes[101] = new opcode { ins = new instruction(adc), adm = new addrmode(zpg) };
		opcodes[102] = new opcode { ins = new instruction(ror), adm = new addrmode(zpg) };
		opcodes[104] = new opcode { ins = new instruction(pla), adm = new addrmode(imp) };
		opcodes[105] = new opcode { ins = new instruction(adc), adm = new addrmode(imm) };
		opcodes[106] = new opcode { ins = new instruction(ror_a), adm = new addrmode(a) };
		opcodes[108] = new opcode { ins = new instruction(jmp), adm = new addrmode(ind) };
		opcodes[109] = new opcode { ins = new instruction(adc), adm = new addrmode(abs) };
		opcodes[110] = new opcode { ins = new instruction(ror), adm = new addrmode(abs) };
		opcodes[112] = new opcode { ins = new instruction(bvs), adm = new addrmode(rel) };
		opcodes[113] = new opcode { ins = new instruction(adc), adm = new addrmode(iny) };
		opcodes[117] = new opcode { ins = new instruction(adc), adm = new addrmode(zpx) };
		opcodes[118] = new opcode { ins = new instruction(ror), adm = new addrmode(zpx) };
		opcodes[120] = new opcode { ins = new instruction(sei), adm = new addrmode(imp) };
		opcodes[121] = new opcode { ins = new instruction(adc), adm = new addrmode(aby) };
		opcodes[125] = new opcode { ins = new instruction(adc), adm = new addrmode(abx) };
		opcodes[126] = new opcode { ins = new instruction(ror), adm = new addrmode(abx) };
		opcodes[129] = new opcode { ins = new instruction(sta), adm = new addrmode(inx) };
		opcodes[132] = new opcode { ins = new instruction(sty), adm = new addrmode(zpg) };
		opcodes[133] = new opcode { ins = new instruction(sta), adm = new addrmode(zpg) };
		opcodes[134] = new opcode { ins = new instruction(stx), adm = new addrmode(zpg) };
		opcodes[136] = new opcode { ins = new instruction(dey), adm = new addrmode(imp) };
		opcodes[138] = new opcode { ins = new instruction(txa), adm = new addrmode(imp) };
		opcodes[140] = new opcode { ins = new instruction(sty), adm = new addrmode(abs) };
		opcodes[141] = new opcode { ins = new instruction(sta), adm = new addrmode(abs) };
		opcodes[142] = new opcode { ins = new instruction(stx), adm = new addrmode(abs) };
		opcodes[144] = new opcode { ins = new instruction(bcc), adm = new addrmode(rel) };
		opcodes[145] = new opcode { ins = new instruction(sta), adm = new addrmode(iny) };
		opcodes[148] = new opcode { ins = new instruction(sty), adm = new addrmode(zpx) };
		opcodes[149] = new opcode { ins = new instruction(sta), adm = new addrmode(zpx) };
		opcodes[150] = new opcode { ins = new instruction(stx), adm = new addrmode(zpy) };
		opcodes[152] = new opcode { ins = new instruction(tya), adm = new addrmode(imp) };
		opcodes[153] = new opcode { ins = new instruction(sta), adm = new addrmode(aby) };
		opcodes[154] = new opcode { ins = new instruction(txs), adm = new addrmode(imp) };
		opcodes[157] = new opcode { ins = new instruction(sta), adm = new addrmode(abx) };
		opcodes[160] = new opcode { ins = new instruction(ldy), adm = new addrmode(imm) };
		opcodes[161] = new opcode { ins = new instruction(lda), adm = new addrmode(inx) };
		opcodes[162] = new opcode { ins = new instruction(ldx), adm = new addrmode(imm) };
		opcodes[164] = new opcode { ins = new instruction(ldy), adm = new addrmode(zpg) };
		opcodes[165] = new opcode { ins = new instruction(lda), adm = new addrmode(zpg) };
		opcodes[166] = new opcode { ins = new instruction(ldx), adm = new addrmode(zpg) };
		opcodes[168] = new opcode { ins = new instruction(tay), adm = new addrmode(imp) };
		opcodes[169] = new opcode { ins = new instruction(lda), adm = new addrmode(imm) };
		opcodes[170] = new opcode { ins = new instruction(tax), adm = new addrmode(imp) };
		opcodes[172] = new opcode { ins = new instruction(ldy), adm = new addrmode(abs) };
		opcodes[173] = new opcode { ins = new instruction(lda), adm = new addrmode(abs) };
		opcodes[174] = new opcode { ins = new instruction(ldx), adm = new addrmode(abs) };
		opcodes[176] = new opcode { ins = new instruction(bcs), adm = new addrmode(rel) };
		opcodes[177] = new opcode { ins = new instruction(lda), adm = new addrmode(iny) };
		opcodes[180] = new opcode { ins = new instruction(ldy), adm = new addrmode(zpx) };
		opcodes[181] = new opcode { ins = new instruction(lda), adm = new addrmode(zpx) };
		opcodes[182] = new opcode { ins = new instruction(ldx), adm = new addrmode(zpy) };
		opcodes[184] = new opcode { ins = new instruction(clv), adm = new addrmode(imp) };
		opcodes[185] = new opcode { ins = new instruction(lda), adm = new addrmode(aby) };
		opcodes[186] = new opcode { ins = new instruction(tsx), adm = new addrmode(imp) };
		opcodes[188] = new opcode { ins = new instruction(ldy), adm = new addrmode(abx) };
		opcodes[189] = new opcode { ins = new instruction(lda), adm = new addrmode(abx) };
		opcodes[190] = new opcode { ins = new instruction(ldx), adm = new addrmode(aby) };
		opcodes[192] = new opcode { ins = new instruction(cpy), adm = new addrmode(imm) };
		opcodes[193] = new opcode { ins = new instruction(cmp), adm = new addrmode(inx) };
		opcodes[196] = new opcode { ins = new instruction(cpy), adm = new addrmode(zpg) };
		opcodes[197] = new opcode { ins = new instruction(cmp), adm = new addrmode(zpg) };
		opcodes[198] = new opcode { ins = new instruction(dec), adm = new addrmode(zpg) };
		opcodes[200] = new opcode { ins = new instruction(iny), adm = new addrmode(imp) };
		opcodes[201] = new opcode { ins = new instruction(cmp), adm = new addrmode(imm) };
		opcodes[202] = new opcode { ins = new instruction(dex), adm = new addrmode(imp) };
		opcodes[204] = new opcode { ins = new instruction(cpy), adm = new addrmode(abs) };
		opcodes[205] = new opcode { ins = new instruction(cmp), adm = new addrmode(abs) };
		opcodes[206] = new opcode { ins = new instruction(dec), adm = new addrmode(abs) };
		opcodes[208] = new opcode { ins = new instruction(bne), adm = new addrmode(rel) };
		opcodes[209] = new opcode { ins = new instruction(cmp), adm = new addrmode(iny) };
		opcodes[213] = new opcode { ins = new instruction(cmp), adm = new addrmode(zpx) };
		opcodes[214] = new opcode { ins = new instruction(dec), adm = new addrmode(zpx) };
		opcodes[216] = new opcode { ins = new instruction(cld), adm = new addrmode(imp) };
		opcodes[217] = new opcode { ins = new instruction(cmp), adm = new addrmode(aby) };
		opcodes[221] = new opcode { ins = new instruction(cmp), adm = new addrmode(abx) };
		opcodes[222] = new opcode { ins = new instruction(dec), adm = new addrmode(abx) };
		opcodes[224] = new opcode { ins = new instruction(cpx), adm = new addrmode(imm) };
		opcodes[225] = new opcode { ins = new instruction(sbc), adm = new addrmode(inx) };
		opcodes[228] = new opcode { ins = new instruction(cpx), adm = new addrmode(zpg) };
		opcodes[229] = new opcode { ins = new instruction(sbc), adm = new addrmode(zpg) };
		opcodes[230] = new opcode { ins = new instruction(inc), adm = new addrmode(zpg) };
		opcodes[232] = new opcode { ins = new instruction(inx), adm = new addrmode(imp) };
		opcodes[233] = new opcode { ins = new instruction(sbc), adm = new addrmode(imm) };
		opcodes[234] = new opcode { ins = new instruction(nop), adm = new addrmode(imp) };
		opcodes[235] = new opcode { ins = new instruction(sbc), adm = new addrmode(imm) };
		opcodes[236] = new opcode { ins = new instruction(cpx), adm = new addrmode(abs) };
		opcodes[237] = new opcode { ins = new instruction(sbc), adm = new addrmode(abs) };
		opcodes[238] = new opcode { ins = new instruction(inc), adm = new addrmode(abs) };
		opcodes[240] = new opcode { ins = new instruction(beq), adm = new addrmode(rel) };
		opcodes[241] = new opcode { ins = new instruction(sbc), adm = new addrmode(iny) };
		opcodes[245] = new opcode { ins = new instruction(sbc), adm = new addrmode(zpx) };
		opcodes[246] = new opcode { ins = new instruction(inc), adm = new addrmode(zpx) };
		opcodes[248] = new opcode { ins = new instruction(sed), adm = new addrmode(imp) };
		opcodes[249] = new opcode { ins = new instruction(sbc), adm = new addrmode(aby) };
		opcodes[253] = new opcode { ins = new instruction(sbc), adm = new addrmode(abx) };
		opcodes[254] = new opcode { ins = new instruction(inc), adm = new addrmode(abx) };
	}
}
